"""El esquema y sus reglas.

Estos tests no comprueban que SQLAlchemy funcione: comprueban que las reglas
del PRODUCTO estan en la base y no solo en el codigo de la aplicacion. Un
CHECK en Postgres protege contra un bug del backend, contra un script de
migracion de datos y contra alguien con psql abierto a las dos de la manana.
Una validacion en Pydantic, no.
"""

from __future__ import annotations

import uuid

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import inspect, select, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import (
    CoachAthlete,
    ExerciseCatalog,
    Mesocycle,
    MesocycleExercise,
    Prescription,
    SessionExercise,
    SetLog,
    TrainingSession,
    User,
    UserRole,
)
from tests.conftest import _alembic_config

EXPECTED_TABLES = {
    "alembic_version",
    "coach_athletes",
    "exercise_catalog",
    "exercise_feedback",
    "memberships",
    "mesocycle_exercises",
    "mesocycles",
    "prescriptions",
    "refresh_tokens",
    "session_exercises",
    "set_logs",
    "training_sessions",
    "users",
}


@pytest.mark.asyncio
async def test_la_migracion_crea_todas_las_tablas(session: AsyncSession) -> None:
    conn = await session.connection()
    names = await conn.run_sync(lambda c: set(inspect(c).get_table_names()))
    assert names == EXPECTED_TABLES


def test_los_modelos_no_se_han_separado_de_las_migraciones(database_url: str) -> None:
    """El test que evita el fallo mas caro de todos.

    Si alguien anade una columna a un modelo y olvida generar la migracion, la
    aplicacion funciona en su maquina y revienta en produccion. `alembic check`
    compara los modelos contra la base migrada y falla si sobra o falta algo.
    """
    try:
        command.check(_alembic_config(database_url))
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - solo al fallar
        pytest.fail(
            "Los modelos y las migraciones han divergido. Genera la revision "
            f"con `alembic revision --autogenerate`.\n{exc}"
        )


# ── Helpers ──────────────────────────────────────────────────────────────────


def _user(role: UserRole = UserRole.ATHLETE, email: str | None = None) -> User:
    suffix = uuid.uuid4().hex[:8]
    return User(
        email=email if email is not None else f"{suffix}@cage.test",
        password_hash="argon2-fake",
        display_name="Test",
        role=role.value,
    )


async def _meso_con_ejercicio(
    session: AsyncSession,
) -> tuple[Mesocycle, MesocycleExercise]:
    coach = _user(UserRole.COACH)
    athlete = _user(UserRole.ATHLETE)
    catalog = ExerciseCatalog(
        name="Press banca",
        muscle="CHEST",
        equipment="Barra",
        rep_lo=6,
        rep_hi=10,
        target_rir=2,
        load_increment_kg=2.5,
    )
    session.add_all([coach, athlete, catalog])
    await session.flush()

    meso = Mesocycle(
        athlete_id=athlete.id,
        coach_id=coach.id,
        name="Push/Pull/Legs",
        total_weeks=6,
        current_week_index=0,
        aggressiveness="Media",
        status="active",
    )
    session.add(meso)
    await session.flush()

    mex = MesocycleExercise(
        mesocycle_id=meso.id,
        catalog_id=catalog.id,
        position=0,
        rep_lo=6,
        rep_hi=10,
        target_rir=2,
        load_increment_kg=2.5,
        starting_load_kg=60.0,
        starting_reps=8,
        starting_sets=3,
    )
    session.add(mex)
    await session.flush()
    return meso, mex


# ── Reglas de usuarios y autoridad ───────────────────────────────────────────


@pytest.mark.asyncio
async def test_el_rol_solo_admite_los_tres_conocidos(session: AsyncSession) -> None:
    session.add(
        User(
            email="rol@cage.test",
            password_hash="h",
            display_name="Test",
            role="gerente",
        )
    )
    with pytest.raises(IntegrityError):
        await session.flush()


@pytest.mark.asyncio
async def test_el_email_se_guarda_en_minusculas(session: AsyncSession) -> None:
    """Sin esto, Jorge@cage.test y jorge@cage.test serian dos cuentas."""
    session.add(_user(email="Jorge@Cage.test"))
    with pytest.raises(IntegrityError):
        await session.flush()


@pytest.mark.asyncio
async def test_no_se_puede_ser_coach_de_uno_mismo(session: AsyncSession) -> None:
    u = _user(UserRole.COACH)
    session.add(u)
    await session.flush()

    session.add(CoachAthlete(coach_id=u.id, athlete_id=u.id))
    with pytest.raises(IntegrityError):
        await session.flush()


@pytest.mark.asyncio
async def test_dos_cuentas_no_comparten_email(session: AsyncSession) -> None:
    session.add(_user(email="dup@cage.test"))
    await session.flush()
    session.add(_user(email="dup@cage.test"))
    with pytest.raises(IntegrityError):
        await session.flush()


# ── Reglas del mesociclo ─────────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_la_semana_actual_no_puede_salirse_del_bloque(
    session: AsyncSession,
) -> None:
    coach, athlete = _user(UserRole.COACH), _user()
    session.add_all([coach, athlete])
    await session.flush()

    session.add(
        Mesocycle(
            athlete_id=athlete.id,
            coach_id=coach.id,
            name="Roto",
            total_weeks=6,
            current_week_index=6,  # indices validos: 0..5
            aggressiveness="Media",
            status="draft",
        )
    )
    with pytest.raises(IntegrityError):
        await session.flush()


@pytest.mark.asyncio
async def test_la_agresividad_usa_los_literales_del_motor(
    session: AsyncSession,
) -> None:
    """'Media', no 'MEDIUM'. Es lo que el motor espera sin traduccion."""
    coach, athlete = _user(UserRole.COACH), _user()
    session.add_all([coach, athlete])
    await session.flush()

    session.add(
        Mesocycle(
            athlete_id=athlete.id,
            coach_id=coach.id,
            name="Roto",
            total_weeks=6,
            aggressiveness="MEDIUM",
            status="draft",
        )
    )
    with pytest.raises(IntegrityError):
        await session.flush()


@pytest.mark.asyncio
async def test_borrar_el_meso_se_lleva_sus_ejercicios(session: AsyncSession) -> None:
    meso, mex = await _meso_con_ejercicio(session)
    mex_id = mex.id

    await session.delete(meso)
    await session.flush()

    found = await session.execute(
        select(MesocycleExercise).where(MesocycleExercise.id == mex_id)
    )
    assert found.scalar_one_or_none() is None


# ── Prescripcion del coach ───────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_el_rango_de_reps_va_entero_o_vacio(session: AsyncSession) -> None:
    """Medio rango no significa nada: el motor no sabria que hacer con el."""
    _, mex = await _meso_con_ejercicio(session)
    session.add(
        Prescription(mesocycle_exercise_id=mex.id, rep_lo=8, rep_hi=None, rest_seconds=150)
    )
    with pytest.raises(IntegrityError):
        await session.flush()


@pytest.mark.asyncio
async def test_un_ejercicio_tiene_como_mucho_una_prescripcion(
    session: AsyncSession,
) -> None:
    _, mex = await _meso_con_ejercicio(session)
    session.add(Prescription(mesocycle_exercise_id=mex.id, rest_seconds=150))
    await session.flush()
    session.add(Prescription(mesocycle_exercise_id=mex.id, rest_seconds=120))
    with pytest.raises(IntegrityError):
        await session.flush()


@pytest.mark.asyncio
async def test_el_descanso_tiene_un_techo_razonable(session: AsyncSession) -> None:
    _, mex = await _meso_con_ejercicio(session)
    session.add(Prescription(mesocycle_exercise_id=mex.id, rest_seconds=7200))
    with pytest.raises(IntegrityError):
        await session.flush()


@pytest.mark.asyncio
async def test_los_campos_en_null_significan_automatico(session: AsyncSession) -> None:
    """Una prescripcion vacia es valida: el coach no toco nada."""
    _, mex = await _meso_con_ejercicio(session)
    p = Prescription(mesocycle_exercise_id=mex.id, rest_seconds=150)
    session.add(p)
    await session.flush()

    assert p.sets is None
    assert p.load_kg is None
    assert p.target_rir is None
    assert p.rest_seconds == 150


# ── Sets registrados: idempotencia ───────────────────────────────────────────


async def _session_exercise(session: AsyncSession) -> SessionExercise:
    meso, mex = await _meso_con_ejercicio(session)
    ts = TrainingSession(mesocycle_id=meso.id, week_number=1, day_label="Push A")
    session.add(ts)
    await session.flush()

    se = SessionExercise(
        session_id=ts.id,
        mesocycle_exercise_id=mex.id,
        position=0,
        planned_load_kg=60.0,
        planned_sets=3,
        policy_version="2026.09",
        why="sin senales para mover la carga",
    )
    session.add(se)
    await session.flush()
    return se


@pytest.mark.asyncio
async def test_el_client_id_impide_duplicar_un_set(session: AsyncSession) -> None:
    """El caso real: la cola sin senal reenvia el mismo set tres veces.

    Sin este UNIQUE el set contaria varias veces y el motor subiria la carga
    por un fantasma.
    """
    se = await _session_exercise(session)
    cid = str(uuid.uuid4())

    session.add(SetLog(client_id=cid, session_exercise_id=se.id, idx=0, reps="8", done=True))
    await session.flush()

    session.add(SetLog(client_id=cid, session_exercise_id=se.id, idx=1, reps="8", done=True))
    with pytest.raises(IntegrityError):
        await session.flush()


@pytest.mark.asyncio
async def test_no_hay_dos_sets_en_el_mismo_indice(session: AsyncSession) -> None:
    se = await _session_exercise(session)
    session.add(
        SetLog(
            client_id=str(uuid.uuid4()),
            session_exercise_id=se.id,
            idx=0,
            reps="8",
            done=True,
        )
    )
    await session.flush()

    session.add(
        SetLog(
            client_id=str(uuid.uuid4()),
            session_exercise_id=se.id,
            idx=0,
            reps="9",
            done=True,
        )
    )
    with pytest.raises(IntegrityError):
        await session.flush()


@pytest.mark.asyncio
async def test_las_reps_se_guardan_como_texto(session: AsyncSession) -> None:
    """'8+2' de un myorep tiene que sobrevivir el viaje de ida y vuelta."""
    se = await _session_exercise(session)
    log = SetLog(
        client_id=str(uuid.uuid4()),
        session_exercise_id=se.id,
        idx=0,
        reps="8+2",
        sub_sets="8,2",
        done=True,
    )
    session.add(log)
    await session.flush()
    session.expunge(log)

    found = await session.get(SetLog, log.id)
    assert found is not None
    assert found.reps == "8+2"
    assert found.sub_sets == "8,2"


@pytest.mark.asyncio
async def test_la_sesion_guarda_la_version_de_la_politica(
    session: AsyncSession,
) -> None:
    """Sin esto, el historico no se puede interpretar cuando cambien las reglas."""
    from app.domain.policy import POLICY_VERSION

    se = await _session_exercise(session)
    assert se.policy_version == POLICY_VERSION


@pytest.mark.asyncio
async def test_las_claves_foraneas_estan_activas(session: AsyncSession) -> None:
    """Guardia del propio banco de pruebas.

    SQLite ignora las FK salvo que se pidan por conexion. Si este test falla,
    todos los de CASCADE de arriba estan pasando sin probar nada.
    """
    result = await session.execute(text("PRAGMA foreign_keys"))
    assert result.scalar() == 1
