"""membresias y rol admin

Anade el modelo de cobro y el tercer rol.

DOS COSAS ESTAN ESCRITAS A MANO, y conviene saber por que:

1. **El CHECK de `users.role`.** Alembic autogenera los CHECK al CREAR una
   tabla, pero NO detecta que uno existente haya cambiado. Si esto no se
   escribiera aqui, la base seguiria rechazando el valor 'admin' y no habria
   forma de crear el primer administrador.

2. **El server_default de `must_change_password`.** La columna es NOT NULL y la
   tabla `users` ya tiene filas en cualquier entorno donde esto se aplique.
   Sin un default, el ALTER falla. Se pone en el ALTER y se quita despues: el
   valor por defecto real lo decide la aplicacion al crear cada usuario.

Revision ID: fa475f5526f7
Revises: c4075012574d
Create Date: 2026-09-14 03:12:31.023859
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fa475f5526f7"
down_revision: str | None = "c4075012574d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: El nombre completo, tal cual esta en la base.
CHECK_NAME = "ck_users_role_valido"
#: El token corto. La convencion de nombres de `app/db/base.py` le antepone
#: "ck_users_": pasarle el nombre completo produce ck_users_ck_users_role_valido.
CHECK_TOKEN = "role_valido"
ROLES_SIN_ADMIN = "role IN ('coach', 'athlete')"
ROLES_CON_ADMIN = "role IN ('admin', 'coach', 'athlete')"


def _set_role_check(condition: str) -> None:
    """Reemplaza el CHECK de `users.role`.

    SQLite no sabe soltar un constraint: hay que reconstruir la tabla entera, y
    de eso se encarga `batch_alter_table`. Postgres si puede, y ahi el rodeo
    seria un bloqueo de tabla innecesario.
    """
    dialect = op.get_context().dialect.name

    if dialect == "sqlite":
        with op.batch_alter_table("users", schema=None) as batch_op:
            batch_op.drop_constraint(CHECK_TOKEN, type_="check")
            batch_op.create_check_constraint(CHECK_TOKEN, condition)
    else:
        # op.f() marca el nombre como definitivo para que la convencion no
        # vuelva a prefijarlo.
        op.drop_constraint(op.f(CHECK_NAME), "users", type_="check")
        op.create_check_constraint(op.f(CHECK_NAME), "users", condition)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ends_on >= starts_on", name=op.f("ck_memberships_periodo_coherente")
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["users.id"],
            name=op.f("fk_memberships_athlete_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_memberships_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
    )
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_memberships_athlete_id"), ["athlete_id"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "must_change_password",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        # El default solo existia para poder rellenar las filas que ya estaban.
        batch_op.alter_column("must_change_password", server_default=None)

    _set_role_check(ROLES_CON_ADMIN)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Las cuentas de admin dejan de ser validas: quien haga este downgrade con
    # administradores creados tiene que reasignarlos ANTES.
    _set_role_check(ROLES_SIN_ADMIN)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("must_change_password")

    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memberships_athlete_id"))

    op.drop_table("memberships")
    # ### end Alembic commands ###
