"""esquema inicial

Revision ID: c4075012574d
Revises:
Create Date: 2026-09-14 00:37:54.737534

Las once tablas del servidor, en una sola revision porque es el punto de
partida: no hay nada desplegado que migrar.

Cosas que conviene saber antes de tocarla:

- Los CHECK de los enums ('Baja'/'Media'/'Alta', los musculos, el feedback) se
  generaron a partir de los StrEnum de `app/domain/schemas.py`. Si anades un
  valor alli, regenera con `alembic revision --autogenerate` en vez de editar
  esta lista a mano.
- OJO: Alembic autogenera los CHECK al CREAR una tabla, pero NO al anadir una
  columna a una tabla que ya existe. Si en una revision futura anades una
  columna con CHECK, tienes que escribirlo a mano.
- `set_logs.client_id` es UNIQUE. Es la clave de idempotencia de la cola de
  sincronizacion: el mismo set reenviado tres veces desde el telefono tiene que
  seguir siendo una fila.
- Esta revision NO se edita nunca mas una vez aplicada en un entorno que no se
  pueda tirar y volver a crear. Los cambios van en la siguiente.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c4075012574d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('coach', 'athlete')", name=op.f("ck_users_role_valido")),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_minusculas")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "coach_athletes",
        sa.Column("coach_id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "coach_id <> athlete_id", name=op.f("ck_coach_athletes_no_autoasignacion")
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["users.id"],
            name=op.f("fk_coach_athletes_athlete_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["users.id"],
            name=op.f("fk_coach_athletes_coach_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("coach_id", "athlete_id", name=op.f("pk_coach_athletes")),
    )
    op.create_table(
        "exercise_catalog",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("muscle", sa.String(length=16), nullable=False),
        sa.Column("equipment", sa.String(length=60), nullable=False),
        sa.Column("rep_lo", sa.Integer(), nullable=False),
        sa.Column("rep_hi", sa.Integer(), nullable=False),
        sa.Column("target_rir", sa.Integer(), nullable=False),
        sa.Column("load_increment_kg", sa.Float(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "muscle IN ('CHEST', 'BACK', 'SHOULDERS', 'BICEPS', 'TRICEPS', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'CALVES', 'ABS')",
            name=op.f("ck_exercise_catalog_musculo_valido"),
        ),
        sa.CheckConstraint(
            "load_increment_kg > 0", name=op.f("ck_exercise_catalog_incremento_positivo")
        ),
        sa.CheckConstraint(
            "rep_lo >= 1 AND rep_hi >= rep_lo", name=op.f("ck_exercise_catalog_rango_reps")
        ),
        sa.CheckConstraint(
            "target_rir >= 0 AND target_rir <= 10", name=op.f("ck_exercise_catalog_rir_valido")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_exercise_catalog_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_catalog")),
    )
    with op.batch_alter_table("exercise_catalog", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exercise_catalog_muscle"), ["muscle"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_exercise_catalog_name"), ["name"], unique=False)

    op.create_table(
        "mesocycles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("coach_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("total_weeks", sa.Integer(), nullable=False),
        sa.Column("current_week_index", sa.Integer(), nullable=False),
        sa.Column("aggressiveness", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("started_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "aggressiveness IN ('Baja', 'Media', 'Alta')",
            name=op.f("ck_mesocycles_agresividad_valida"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'completed', 'archived')",
            name=op.f("ck_mesocycles_estado_valido"),
        ),
        sa.CheckConstraint(
            "current_week_index >= 0 AND current_week_index < total_weeks",
            name=op.f("ck_mesocycles_semana_actual_dentro_del_bloque"),
        ),
        sa.CheckConstraint(
            "total_weeks >= 2 AND total_weeks <= 24", name=op.f("ck_mesocycles_semanas_validas")
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["users.id"],
            name=op.f("fk_mesocycles_athlete_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["users.id"],
            name=op.f("fk_mesocycles_coach_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mesocycles")),
    )
    with op.batch_alter_table("mesocycles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mesocycles_athlete_id"), ["athlete_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_mesocycles_coach_id"), ["coach_id"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "mesocycle_exercises",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mesocycle_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rep_lo", sa.Integer(), nullable=False),
        sa.Column("rep_hi", sa.Integer(), nullable=False),
        sa.Column("target_rir", sa.Integer(), nullable=False),
        sa.Column("load_increment_kg", sa.Float(), nullable=False),
        sa.Column("starting_load_kg", sa.Float(), nullable=False),
        sa.Column("starting_reps", sa.Integer(), nullable=False),
        sa.Column("starting_sets", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "load_increment_kg > 0", name=op.f("ck_mesocycle_exercises_incremento_positivo")
        ),
        sa.CheckConstraint(
            "rep_lo >= 1 AND rep_hi >= rep_lo", name=op.f("ck_mesocycle_exercises_rango_reps")
        ),
        sa.CheckConstraint(
            "starting_load_kg > 0", name=op.f("ck_mesocycle_exercises_carga_inicial_positiva")
        ),
        sa.CheckConstraint(
            "starting_reps >= 1 AND starting_sets >= 1",
            name=op.f("ck_mesocycle_exercises_arranque_positivo"),
        ),
        sa.CheckConstraint(
            "target_rir >= 0 AND target_rir <= 10",
            name=op.f("ck_mesocycle_exercises_rir_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["exercise_catalog.id"],
            name=op.f("fk_mesocycle_exercises_catalog_id_exercise_catalog"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mesocycle_id"],
            ["mesocycles.id"],
            name=op.f("fk_mesocycle_exercises_mesocycle_id_mesocycles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mesocycle_exercises")),
        sa.UniqueConstraint(
            "mesocycle_id",
            "position",
            name=op.f("uq_mesocycle_exercises_mesocycle_id_position"),
        ),
    )
    op.create_table(
        "training_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mesocycle_id", sa.Uuid(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=False),
        sa.Column("day_label", sa.String(length=60), nullable=False),
        sa.Column("is_deload", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR started_at IS NOT NULL",
            name=op.f("ck_training_sessions_no_se_cierra_sin_abrir"),
        ),
        sa.CheckConstraint(
            "week_number >= 1", name=op.f("ck_training_sessions_semana_positiva")
        ),
        sa.ForeignKeyConstraint(
            ["mesocycle_id"],
            ["mesocycles.id"],
            name=op.f("fk_training_sessions_mesocycle_id_mesocycles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_sessions")),
    )
    with op.batch_alter_table("training_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_training_sessions_mesocycle_id"), ["mesocycle_id"], unique=False
        )

    op.create_table(
        "prescriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mesocycle_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=True),
        sa.Column("load_kg", sa.Float(), nullable=True),
        sa.Column("rep_lo", sa.Integer(), nullable=True),
        sa.Column("rep_hi", sa.Integer(), nullable=True),
        sa.Column("target_rir", sa.Integer(), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=False),
        sa.Column("set_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(rep_lo IS NULL AND rep_hi IS NULL) OR (rep_lo IS NOT NULL AND rep_hi IS NOT NULL AND rep_hi >= rep_lo)",
            name=op.f("ck_prescriptions_rango_completo_o_vacio"),
        ),
        sa.CheckConstraint(
            "load_kg IS NULL OR load_kg > 0", name=op.f("ck_prescriptions_carga_positiva")
        ),
        sa.CheckConstraint(
            "rest_seconds > 0 AND rest_seconds <= 900",
            name=op.f("ck_prescriptions_descanso_razonable"),
        ),
        sa.CheckConstraint(
            "sets IS NULL OR sets >= 1", name=op.f("ck_prescriptions_sets_positivos")
        ),
        sa.ForeignKeyConstraint(
            ["mesocycle_exercise_id"],
            ["mesocycle_exercises.id"],
            name=op.f("fk_prescriptions_mesocycle_exercise_id_mesocycle_exercises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["set_by_id"],
            ["users.id"],
            name=op.f("fk_prescriptions_set_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prescriptions")),
        sa.UniqueConstraint(
            "mesocycle_exercise_id", name=op.f("uq_prescriptions_mesocycle_exercise_id")
        ),
    )
    op.create_table(
        "session_exercises",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("mesocycle_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("planned_load_kg", sa.Float(), nullable=False),
        sa.Column("planned_sets", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.String(length=16), nullable=False),
        sa.Column("why", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "planned_load_kg > 0", name=op.f("ck_session_exercises_carga_planificada")
        ),
        sa.CheckConstraint(
            "planned_sets >= 1", name=op.f("ck_session_exercises_sets_planificados")
        ),
        sa.ForeignKeyConstraint(
            ["mesocycle_exercise_id"],
            ["mesocycle_exercises.id"],
            name=op.f("fk_session_exercises_mesocycle_exercise_id_mesocycle_exercises"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_session_exercises_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_exercises")),
        sa.UniqueConstraint(
            "session_id",
            "mesocycle_exercise_id",
            name=op.f("uq_session_exercises_session_id_mesocycle_exercise_id"),
        ),
    )
    op.create_table(
        "exercise_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("joint", sa.String(length=32), nullable=False),
        sa.Column("soreness", sa.String(length=32), nullable=False),
        sa.Column("pump", sa.String(length=32), nullable=False),
        sa.Column("volume", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "joint IN ('Ninguno', 'Poco', 'Moderado', 'Mucho')",
            name=op.f("ck_exercise_feedback_dolor_valido"),
        ),
        sa.CheckConstraint(
            "pump IN ('Bajo', 'Moderado', 'Increíble')",
            name=op.f("ck_exercise_feedback_pump_valido"),
        ),
        sa.CheckConstraint(
            "soreness IN ('Nunca me dolió', 'Se fue hace días', 'Se fue justo a tiempo', 'Aún me duele')",
            name=op.f("ck_exercise_feedback_agujetas_validas"),
        ),
        sa.CheckConstraint(
            "volume IN ('Insuficiente', 'Justo', 'Al límite', 'Demasiado')",
            name=op.f("ck_exercise_feedback_volumen_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["session_exercise_id"],
            ["session_exercises.id"],
            name=op.f("fk_exercise_feedback_session_exercise_id_session_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_feedback")),
        sa.UniqueConstraint(
            "session_exercise_id", name=op.f("uq_exercise_feedback_session_exercise_id")
        ),
    )
    op.create_table(
        "set_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("session_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("reps", sa.String(length=16), nullable=True),
        sa.Column("rpe", sa.String(length=16), nullable=True),
        sa.Column("sub_sets", sa.String(length=32), nullable=True),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("logged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("idx >= 0", name=op.f("ck_set_logs_indice_no_negativo")),
        sa.CheckConstraint(
            "weight_kg IS NULL OR weight_kg >= 0", name=op.f("ck_set_logs_peso_valido")
        ),
        sa.ForeignKeyConstraint(
            ["session_exercise_id"],
            ["session_exercises.id"],
            name=op.f("fk_set_logs_session_exercise_id_session_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_set_logs")),
        sa.UniqueConstraint("client_id", name=op.f("uq_set_logs_client_id")),
        sa.UniqueConstraint(
            "session_exercise_id", "idx", name=op.f("uq_set_logs_session_exercise_id_idx")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("set_logs")
    op.drop_table("exercise_feedback")
    op.drop_table("session_exercises")
    op.drop_table("prescriptions")
    with op.batch_alter_table("training_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_sessions_mesocycle_id"))

    op.drop_table("training_sessions")
    op.drop_table("mesocycle_exercises")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("mesocycles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mesocycles_coach_id"))
        batch_op.drop_index(batch_op.f("ix_mesocycles_athlete_id"))

    op.drop_table("mesocycles")
    with op.batch_alter_table("exercise_catalog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exercise_catalog_name"))
        batch_op.drop_index(batch_op.f("ix_exercise_catalog_muscle"))

    op.drop_table("exercise_catalog")
    op.drop_table("coach_athletes")
    op.drop_table("users")
    # ### end Alembic commands ###
