"""marcas de 1RM por atleta

Tabla nueva, `one_rep_maxes`. Nace porque los basicos se programan por
porcentaje: sin el maximo del atleta, un "75%" no es un peso.

**Es un historial.** Cada test anade una fila; ninguna sobrescribe a la
anterior. La marca vigente es la mas reciente y se calcula al leer. Si fuera un
campo mutable, subir el maximo reescribiria en silencio los pesos de todos los
bloques ya programados.

El UNIQUE de (atleta, ejercicio, fecha) impide el dedazo de apuntar dos veces
el mismo test; no impide dos marcas del mismo ejercicio en fechas distintas,
que es justo el caso normal.

Aqui los CHECK SI los autogenero Alembic, al contrario que en migraciones
anteriores: los detecta al crear una tabla, y solo se le escapan al anadir una
columna a una que ya existe. Se revisaron uno por uno de todas formas.

Revision ID: 939441e39196
Revises: a1c7d3e4b592
Create Date: 2026-09-21 00:32:34.107644
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "939441e39196"
down_revision: str | None = "a1c7d3e4b592"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "one_rep_maxes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("value_kg", sa.Float(), nullable=False),
        sa.Column("achieved_on", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("set_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('test', 'competicion', 'estimada')",
            name=op.f("ck_one_rep_maxes_origen_valido"),
        ),
        sa.CheckConstraint(
            "value_kg > 0 AND value_kg <= 600", name=op.f("ck_one_rep_maxes_marca_razonable")
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["users.id"],
            name=op.f("fk_one_rep_maxes_athlete_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercise_catalog.id"],
            name=op.f("fk_one_rep_maxes_exercise_id_exercise_catalog"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["set_by_id"],
            ["users.id"],
            name=op.f("fk_one_rep_maxes_set_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_one_rep_maxes")),
        sa.UniqueConstraint(
            "athlete_id",
            "exercise_id",
            "achieved_on",
            name=op.f("uq_one_rep_maxes_athlete_id_exercise_id_achieved_on"),
        ),
    )
    with op.batch_alter_table("one_rep_maxes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_one_rep_maxes_athlete_id"), ["athlete_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_one_rep_maxes_exercise_id"), ["exercise_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("one_rep_maxes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_one_rep_maxes_exercise_id"))
        batch_op.drop_index(batch_op.f("ix_one_rep_maxes_athlete_id"))

    op.drop_table("one_rep_maxes")
    # ### end Alembic commands ###
