"""objetivo y prescripciones por semana

Dos cambios de producto:

1. **`mesocycles.goal`** — fuerza, hipertrofia o hibrido. No cambia como
   calcula el motor: decide con que valores por defecto entra cada ejercicio.
   Se pone `hipertrofia` a las filas existentes porque es lo que el prototipo
   asumia.

2. **`prescriptions.week_number`** — la prescripcion gana la dimension semana.
   NULL sigue significando "vale para todo el bloque", que es exactamente lo
   que eran todas las filas hasta ahora, asi que no hay datos que convertir.

ESCRITO A MANO: los dos CHECK. Alembic autogenera los CHECK al crear una tabla
pero no al anadir una columna, asi que sin esto la base aceptaria un objetivo
inventado y una semana cero.

Revision ID: 9a1c36985ffd
Revises: fa475f5526f7
Create Date: 2026-09-16 01:03:28.237232
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9a1c36985ffd"
down_revision: str | None = "fa475f5526f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mesocycles", schema=None) as batch_op:
        # server_default para poder rellenar las filas que ya existen; se
        # quita despues porque el valor real lo decide la aplicacion.
        batch_op.add_column(
            sa.Column(
                "goal",
                sa.String(length=12),
                nullable=False,
                server_default="hipertrofia",
            )
        )
        batch_op.alter_column("goal", server_default=None)
        batch_op.create_check_constraint(
            "objetivo_valido", "goal IN ('fuerza', 'hipertrofia', 'hibrido')"
        )

    with op.batch_alter_table("prescriptions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("week_number", sa.Integer(), nullable=True))
        batch_op.drop_constraint(
            batch_op.f("uq_prescriptions_mesocycle_exercise_id"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_prescriptions_mesocycle_exercise_id_week_number"),
            ["mesocycle_exercise_id", "week_number"],
        )
        batch_op.create_check_constraint(
            "semana_valida", "week_number IS NULL OR week_number >= 1"
        )

    # Indice parcial: impide DOS prescripciones base para el mismo ejercicio.
    #
    # El UNIQUE de (ejercicio, semana) no lo cubre: tanto SQLite como Postgres
    # consideran que dos NULL son valores distintos, asi que sin esto podrian
    # coexistir dos bases y cual mandaria seria arbitrario.
    op.create_index(
        "uq_prescriptions_base",
        "prescriptions",
        ["mesocycle_exercise_id"],
        unique=True,
        sqlite_where=sa.text("week_number IS NULL"),
        postgresql_where=sa.text("week_number IS NULL"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_prescriptions_base", table_name="prescriptions")

    with op.batch_alter_table("prescriptions", schema=None) as batch_op:
        batch_op.drop_constraint("semana_valida", type_="check")
        batch_op.drop_constraint(
            batch_op.f("uq_prescriptions_mesocycle_exercise_id_week_number"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_prescriptions_mesocycle_exercise_id"), ["mesocycle_exercise_id"]
        )
        batch_op.drop_column("week_number")

    with op.batch_alter_table("mesocycles", schema=None) as batch_op:
        batch_op.drop_constraint("objetivo_valido", type_="check")
        batch_op.drop_column("goal")

    # ### end Alembic commands ###
